<?php
/**
 * Appmerce - Applications for Ecommerce
 * http://www.appmerce.com
 *
 * @extension   Bitcoin
 * @type        Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    Magento Commerce
 * @package     Appmerce_Bitcoin
 * @copyright   Copyright (c) 2011-2013 Appmerce (http://www.appmerce.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<p>
<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?><br />
<?php if ($this->getAddress()): ?>
    <?php echo Mage::helper('bitcoin')->__('Please send exactly %s BTC to:', $this->getAmount()); ?><br />
    <pre><?php echo $this->getAddress(); ?></pre>
    <a href="<?php echo $this->getBitcoin(); ?>">
        <img src="<?php echo $this->getQr(75); ?>" />
    </a>
<?php elseif ($this->getQuoteAmount()): ?>
    <?php echo Mage::helper('bitcoin')->__('%s BTC', $this->getQuoteAmount()); ?>
<?php endif; ?>